[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi=true
verbosity=5
openzeppelin-contracts = { path = "lib/openzeppelin-contracts"}
remmaping = [[
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@arachnid/=lib/solidity-stringutils/src/",
]]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
